
library(ggplot2)

load("./results_model_calibration/SIR-calibration_optim.RData")
load("./results_model_calibration/SIR-calibration.RData")
reference <- as.data.frame(read.csv("./Input/reference_data.csv",
                                      header = FALSE,
                                      sep = ""))
calibration_optim_trace <-read.csv("./results_model_calibration/SIR-calibration_optim-trace.csv",sep = "")


# Then, we read all the trajectories generated saving them in a list called
# ListTraces. List that will be rewritten as a data frame in order to use ggplot.
# ConfigID represents the initial condition associated to each trajectory,
# which was generated by using the function implemented in the file Functions.R .

listFile<-list.files("./results_model_calibration/",
                     pattern = ".trace")

id.traces<-calibration_optim_trace$id

ListTraces<-lapply(id.traces,
                   function(x){
                     trace.tmp=read.csv(paste0(
                       "./results_model_calibration/SIR-calibration-",
                       x,
                       ".trace"), sep = "")
                     trace.tmp=data.frame(trace.tmp,ID=calibration_optim_trace$distance[which(calibration_optim_trace$id==x)])
                     return(trace.tmp)
                   })

traces <- do.call("rbind", ListTraces)

plI<-ggplot( )+
  geom_line(data=traces,
            aes(x=Time/7,y=I,group=ID,col=ID))+
  geom_line(data=reference,
            aes(x=V1/7,y=V3),
            col="red")+
  theme(axis.text=element_text(size=18),
        axis.title=element_text(size=20,face="bold"),
        legend.text=element_text(size=18),
        legend.title=element_text(size=20,face="bold"),
        legend.position="right",
        legend.key.size = unit(1.3, "cm"),
        legend.key.width = unit(1.3,"cm") )+
  labs(x="Weeks", y="I",col="Distance")

ggsave("./plI_calibration.pdf")

plS<-ggplot( )+
  geom_line(data=traces,
            aes(x=Time/7,y=S,group=ID,col=ID))+
  geom_line(data=reference,
            aes(x=V1/7,y=V2),
            col="red")+
  theme(axis.text=element_text(size=18),
        axis.title=element_text(size=20,face="bold"),
        legend.text=element_text(size=18),
        legend.title=element_text(size=20,face="bold"),
        legend.position="right",
        legend.key.size = unit(1.3, "cm"),
        legend.key.width = unit(1.3,"cm") )+
  labs(x="Weeks", y="S",col="Distance")

ggsave("./plS_calibration.pdf")

plR<-ggplot( )+
  geom_line(data=traces,
            aes(x=Time/7,y=R,group=ID,col=ID))+
  geom_line(data=reference,
            aes(x=V1/7,y=V4),
            col="red")+
  theme(axis.text=element_text(size=18),
        axis.title=element_text(size=20,face="bold"),
        legend.text=element_text(size=18),
        legend.title=element_text(size=20,face="bold"),
        legend.position="right",
        legend.key.size = unit(1.3, "cm"),
        legend.key.width = unit(1.3,"cm") )+
  labs(x="Weeks", y="R",col="Distance")

ggsave("./plR_calibration.pdf")
