
##############################
## Let draw the orbits characterizing the phase-space
##############################

library(ggplot2)

# First we load the RData storing the configurations generated
# by the sensitivity analysis. (uncomment the second if you want the ranking!)

#load("./PredyPredator/results/PredyPredator-sensitivity.RData")
load("./PredyPredator/results/ranking_PredyPredator-sensitivity.RData")
reference <- as.data.frame(t(read.csv("reference_data.csv", header = FALSE, sep = "")))

# Then, we read all the trajectories generated saving them in a list called ListTraces. List that will be rewritten as a data frame in order to use ggplot.
# ConfigID represents the initial condition associated to each trajectory, which was generated by using the function implemented in the file Functions.R .

listFile<-list.files("./PredyPredator/results/",
                     pattern = ".trace")

configID<-t(sapply(1:length(listFile),
                   function(x){
                       return(c(x,config[[1]][[x]][[3]]))
                   }) )

id.traces<-as.numeric(gsub("[^[:digit:].]", "",listFile) )

ListTraces<-lapply(id.traces,
                   function(x){
                       trace.tmp=read.csv(paste0("./PredyPredator/results/PredyPredator-sensitivity-",x,".trace"), sep = "")
                       # IMPORTANT: uncomment the second if you want the ranking!
                       # trace.tmp=data.frame(trace.tmp,ID=configID[which(configID[,1]==x),2])
                       trace.tmp=data.frame(trace.tmp,ID=rank[which(rank[,2]==x),1])
                       return(trace.tmp)
                   })

traces <- do.call("rbind", ListTraces)

# without reference
ggplot(traces,aes(x=Prey,y=Predator,group=ID,col=ID) )+
    geom_path(arrow=arrow(length=unit(0.3,"cm"),ends="first"))
# with reference
ggplot( )+
    geom_path(data=traces,aes(x=Prey,y=Predator,group=ID,col=ID),arrow=arrow(length=unit(0.3,"cm"),ends="first"))+
    geom_path(data=reference,aes(x=V1,y=V2), col="red", arrow=arrow(length=unit(0.3,"cm"),ends="first"))
